#gt915 touchpanel driver

EXTRA_CFLAGS += $(call cc-disable-warning, date-time)

obj-$(CONFIG_GT9XX_TOUCHPANEL_DRIVER)	+= gt9xx.o
obj-$(CONFIG_GT9XX_TOUCHPANEL_UPDATE)	+= gt9xx_update.o
obj-$(CONFIG_GT9XX_TOUCHPANEL_DEBUG)	+= goodix_tool.o
