#
# Makefile for the Synaptics DSX touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_TD4310) += synaptics_dsx_i2c.o
obj-$(CONFIG_TOUCHSCREEN_TD4310) += synaptics_dsx_core.o
obj-$(CONFIG_TOUCHSCREEN_TD4310) += synaptics_dsx_rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_TD4310) += synaptics_dsx_fw_update.o
obj-$(CONFIG_TOUCHSCREEN_TD4310) += synaptics_dsx_test_reporting.o
