#gt915 touchpanel driver

EXTRA_CFLAGS += $(call cc-disable-warning, date-time)

obj-$(CONFIG_TOUCHSCREEN_GT9XX_v24)		+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_v24_UPDATE)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_v24_TOOL)	+= goodix_tool.o
